import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const { chromium } = await import(process.env.CL_PLAYWRIGHT_URL || 'playwright');
const output = fileURLToPath(new URL('../../backups/ui34_visual_audit_20260910/', import.meta.url));
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, ...(process.env.CL_CHROME_PATH ? { executablePath: process.env.CL_CHROME_PATH } : {}) });
const viewports = [['phone-360',360,800],['phone-390',390,844],['phone-430',430,932],['tablet-768',768,1024],['desktop-1200',1200,900],['wall-1920',1920,1080]];
const themes = ['auto','light','dark','cl_blue','night','contrast'];
const results = [];

for (const theme of themes) for (const [name,width,height] of viewports) {
  const page = await browser.newPage({ viewport:{width,height}, deviceScaleFactor:1 });
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:8765/tests/ui3-harness.html?theme=${theme}`,{waitUntil:'networkidle'});
  await page.waitForSelector('cl-control-panel');await page.waitForTimeout(650);
  const common=await page.locator('cl-control-panel').evaluate(element=>{const root=element.shadowRoot;if(!root)return{upgraded:false};const app=root.querySelector('.app'),nav=root.querySelector('.nav'),buttons=[...nav.querySelectorAll('button')],visible=buttons.filter(button=>getComputedStyle(button).display!=='none'),customerPages=[...root.querySelectorAll('.page')].filter(section=>!['page-more'].includes(section.id)),customerText=customerPages.map(section=>section.textContent||'').join(' '),touch=[...root.querySelectorAll('button,input,select')].filter(node=>{if(node.type==='range')return false;const rect=node.getBoundingClientRect();return rect.width>0&&rect.height>0&&(rect.width<44||rect.height<44)}),rects=visible.map(button=>button.getBoundingClientRect()),sidebarOverlap=innerWidth>=768&&rects.some((rect,index)=>index>0&&rect.top<rects[index-1].bottom-.5),allPages=buttons.map(button=>button.dataset.page).filter(id=>id!=='overflow'),direct=visible.map(button=>button.dataset.page).filter(id=>id!=='overflow'),overflow=[...root.querySelectorAll('[data-overflow-open]')].map(button=>button.dataset.overflowOpen),missing=innerWidth<768?allPages.filter(id=>!direct.includes(id)&&!overflow.includes(id)):[];return{upgraded:true,documentOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,appOverflow:app.scrollWidth>app.clientWidth,navItemsVisible:visible.length,touchTargetsTooSmall:touch.length,forbiddenBrand:/Home Control/.test(customerText),customerEntityId:/\b(?:light|switch|sensor|cover|climate|camera|binary_sensor|alarm_control_panel)\.[a-z0-9_]+\b/i.test(customerText),technicalName:/shelly|profile_name/i.test(customerText),unresolvedName:/Nome da configurare|Nome non configurato/i.test(customerText),statusSeparated:getComputedStyle(root.querySelector('.statusTitle')).display==='block'&&getComputedStyle(root.querySelector('.statusMeta')).display==='block',cardBackground:getComputedStyle(root.querySelector('.quickTile')).backgroundColor,sidebarOverlap,missingPages:missing,logoSize:Math.round(root.querySelector('.logo')?.getBoundingClientRect().width||0),offenders:[...root.querySelectorAll('*')].map(node=>({node:`${node.tagName.toLowerCase()}.${node.className||''}`,rect:node.getBoundingClientRect()})).filter(item=>item.rect.width>0&&(item.rect.right>document.documentElement.clientWidth+.5||item.rect.left<-.5)).slice(0,8).map(item=>item.node)};});
  const brandLink=await page.locator('cl-control-panel').evaluate(element=>{const link=element.shadowRoot.querySelector('.brandHome');return{href:link?.href||'',aria:link?.getAttribute('aria-label')||'',expected:new URL('/',location.origin).href};});
  if(!common.upgraded)throw new Error(`Custom element non inizializzato: ${errors.join(' | ')}`);

  await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-page="lights"]')?.click());await page.waitForTimeout(80);
  const light=await page.locator('cl-control-panel').evaluate(element=>{const root=element.shadowRoot,toggles=[...root.querySelectorAll('#page-lights .clToggle')],advanced=root.querySelector('[data-light-card][data-light-advanced="true"]');advanced?.click();return{toggleSizesOk:toggles.every(toggle=>toggle.getBoundingClientRect().width>=44&&toggle.getBoundingClientRect().height>=44),hasOn:toggles.some(toggle=>toggle.getAttribute('aria-checked')==='true'),hasOff:toggles.some(toggle=>toggle.getAttribute('aria-checked')==='false'&&!toggle.disabled),hasUnavailable:toggles.some(toggle=>toggle.disabled&&toggle.textContent.includes('Non disponibile')),hasAdvanced:Boolean(advanced),hasNativeColor:Boolean(root.querySelector('input[type="color"]'))};});await page.waitForTimeout(30);
  const colorDialog=await page.locator('cl-control-panel').evaluate(element=>Boolean(element.shadowRoot.querySelector('.colorWheel')&&element.shadowRoot.querySelector('.lightSheet')));await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-dialog-cancel]')?.click());
  await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-toggle-light="light.soggiorno"]')?.click());await page.waitForTimeout(25);const loading=await page.locator('cl-control-panel').evaluate(element=>{const toggle=element.shadowRoot.querySelector('[data-toggle-light="light.soggiorno"]');return Boolean(toggle?.classList.contains('loading')&&toggle.disabled&&toggle.getAttribute('aria-busy')==='true')});

  const modules={};for(const [id,selector] of [['covers','.coverSlider'],['climate','.thermostatCard'],['security','.zoneRow'],['cameras','.camera']]){await page.locator('cl-control-panel').evaluate((element,pageId)=>element.shadowRoot.querySelector(`[data-page="${pageId}"]`)?.click(),id);await page.waitForTimeout(35);modules[id]=await page.locator('cl-control-panel').evaluate((element,query)=>Boolean(element.shadowRoot.querySelector(query)),selector);}
  await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-page="climate"]')?.click());await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-climate-open]')?.click());await page.waitForTimeout(25);modules.climateDialog=await page.locator('cl-control-panel').evaluate(element=>Boolean(element.shadowRoot.querySelector('.climateSheet')));await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-dialog-cancel]')?.click());
  await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-page="cameras"]')?.click());await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-camera]')?.click());await page.waitForTimeout(25);modules.cameraViewer=await page.locator('cl-control-panel').evaluate(element=>Boolean(element.shadowRoot.querySelector('.cameraViewer')));await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-dialog-cancel]')?.click());

  let installer=null;if(['phone-390','tablet-768','desktop-1200'].includes(name)){await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-page="more"]')?.click());await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('#unlockInstaller')?.click());await page.locator('cl-control-panel').evaluate(element=>{const input=element.shadowRoot.querySelector('#clPin');if(input){input.value='1234';element.shadowRoot.querySelector('#clDialogForm')?.requestSubmit()}});await page.waitForTimeout(120);await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-review-entity]')?.click());await page.waitForTimeout(40);installer=await page.locator('cl-control-panel').evaluate(element=>{const root=element.shadowRoot,section=root.querySelector('#page-more'),choices=[...root.querySelectorAll('.choiceOption')],labels=choices.map(choice=>choice.textContent.trim());return{rows:root.querySelectorAll('.reviewRow').length,filters:root.querySelectorAll('[data-review-filter]').length,nativeHa:Boolean(root.querySelector('#openNativeHa')),overflow:section.scrollWidth>section.clientWidth,entityIdsWrapped:[...root.querySelectorAll('.reviewMain code')].every(code=>code.scrollWidth<=code.clientWidth+1),compactChoices:Boolean(root.querySelector('.choicePicker')),noNativeEntitySelect:!root.querySelector('#clDialogForm select[name="module"]'),choiceTouch:choices.every(choice=>choice.getBoundingClientRect().height>=44),italianModules:['Auto','Luci','Aperture','Clima','Energia','Sicurezza','Telecamere','Assistenza','Installer'].every(label=>labels.includes(label))}});await page.screenshot({path:join(output,`${theme}-${name}-installer.png`),fullPage:true});await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-dialog-cancel]')?.click());}
  await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-page="home"]')?.click());
  const area=await page.locator('cl-control-panel').evaluate(element=>{const root=element.shadowRoot,card=root.querySelector('[data-home-area]');card?.click();const view=root.querySelector('#page-area'),sections=[...root.querySelectorAll('#page-area [data-area-section]')],tiles=[...root.querySelectorAll('#page-area .clTile')],chips=[...root.querySelectorAll('#page-area .environmentChip')];return{available:Boolean(card),active:view?.classList.contains('active'),sections:sections.length,tiles:tiles.length,chips:chips.length,overflow:Boolean(view&&view.scrollWidth>view.clientWidth),emptySections:sections.filter(section=>!section.querySelector('.clTile')).length,touchOk:[...tiles,...chips].every(node=>{const rect=node.getBoundingClientRect();return rect.width>=44&&rect.height>=44})};});await page.waitForTimeout(30);await page.screenshot({path:join(output,`${theme}-${name}-area.png`),fullPage:true});await page.locator('cl-control-panel').evaluate(element=>element.shadowRoot.querySelector('[data-area-back]')?.click());await page.screenshot({path:join(output,`${theme}-${name}-home.png`),fullPage:true});
  let desktopStress=null;if(name==='desktop-1200'){await page.setViewportSize({width:1200,height:560});desktopStress=[];for(const zoom of [1,1.25,1.5])desktopStress.push(await page.locator('cl-control-panel').evaluate((element,value)=>{element.style.zoom=String(value);const nav=element.shadowRoot.querySelector('.nav'),rects=[...nav.querySelectorAll('button')].filter(button=>getComputedStyle(button).display!=='none').map(button=>button.getBoundingClientRect());return{zoom:value,overlap:rects.some((rect,index)=>index>0&&rect.top<rects[index-1].bottom-.5),scrollEnabled:getComputedStyle(nav).overflowY==='auto',clientHeight:nav.clientHeight,scrollHeight:nav.scrollHeight}},zoom));}
  results.push({theme,name,width,height,...common,brandLink,...light,colorDialog,loading,modules,area,installer,desktopStress,errors});await page.close();
}
await browser.close();console.log('visual audit completed:',results.length,'combinations');
const dark=results.find(result=>result.theme==='cl_blue'&&result.name==='phone-390');
const light=results.find(result=>result.theme==='light'&&result.name==='phone-390');
const resultFailed=result=>!result.upgraded
  ||result.documentOverflow||result.appOverflow||result.errors.length
  ||(result.width<768&&result.navItemsVisible>5)||result.touchTargetsTooSmall
  ||result.forbiddenBrand||result.customerEntityId||result.technicalName||result.unresolvedName
  ||!result.statusSeparated||result.sidebarOverlap||result.missingPages.length||result.offenders.length
  ||!result.toggleSizesOk||!result.hasOn||!result.hasOff||!result.hasUnavailable
  ||result.hasNativeColor||!result.hasAdvanced||!result.colorDialog||!result.loading
  ||Object.values(result.modules).some(value=>!value)
  ||!result.area.available||!result.area.active||!result.area.sections||!result.area.tiles||result.area.overflow||result.area.emptySections||!result.area.touchOk
  ||result.brandLink.href!==result.brandLink.expected||result.brandLink.aria!=='Apri Home Assistant'
  ||(result.width<768&&(result.logoSize<50||result.logoSize>54))
  ||(result.width>=768&&(result.logoSize<56||result.logoSize>60))
  ||(result.installer&&(!result.installer.rows||result.installer.filters<5||!result.installer.nativeHa||result.installer.overflow||!result.installer.entityIdsWrapped||!result.installer.compactChoices||!result.installer.noNativeEntitySelect||!result.installer.choiceTouch||!result.installer.italianModules))
  ||(result.desktopStress&&result.desktopStress.some(stress=>stress.overlap||!stress.scrollEnabled));
const failed=results.some(resultFailed)||dark?.cardBackground===light?.cardBackground;
if(failed)console.log(JSON.stringify(results.filter(resultFailed),null,2));
if(failed)process.exitCode=1;
