"""Branding module defaults."""

DEFAULT_CONFIG = {
    "schema_version": 1,
    "brand_name": "CL Control",
    "company_name": "CL Impianti",
    "product_name": "CL Control",
    "tagline": "Home & Building Control",
    "mode": "enhanced",
    "rename_instance": False,
    "pwa_branding": True,
    "browser_title": True,
    "sidebar_title": True,
    "favicon": True,
    "assets": {
        "logo": "frontend:logo.png",
        "logo_compact": "frontend:logo.png",
        "favicon": "",
    },
    "colors": {
        "primary": "#19BAFF",
        "secondary": "#164C78",
        "accent": "#32E394",
        "background": "#061324",
        "surface": "#123852",
        "surface_alt": "#071D34",
        "text": "#F4F9FF",
        "muted": "#8FA9C5",
        "warning": "#FFD05C",
        "danger": "#FF5B69",
        "line": "rgba(140, 201, 255, 0.18)",
        "light_default_rgb": "255, 208, 92",
    },
    "typography": {
        "font_family": "Inter, system-ui, -apple-system, Segoe UI, sans-serif",
        "font_url": "",
    },
    "design_tokens": {
        "spacing": {"xs": "4px", "sm": "8px", "md": "12px", "lg": "16px", "xl": "24px", "xxl": "32px"},
        "radius": {"sm": "8px", "md": "12px", "lg": "18px", "xl": "24px", "pill": "999px"},
        "shadow": {
            "low": "0 4px 14px rgba(0, 0, 0, 0.12)",
            "medium": "0 12px 30px rgba(0, 0, 0, 0.18)",
            "high": "0 20px 48px rgba(0, 0, 0, 0.24)",
        },
        "icon_size": {"sm": "18px", "md": "22px", "lg": "28px"},
        "typography_scale": {"micro": "8px", "caption": "9px", "label": "10px", "body_small": "11px", "body": "12px", "heading": "15px", "title": "20px", "display": "30px"},
        "component_size": {"content_max_width": "1280px", "dashboard_content_max_width": "1600px", "logo": "72px", "camera_height": "200px", "navigation_max_width": "960px", "navigation_item_width": "82px", "panel_bottom_space": "96px", "dashboard_bottom_nav": "56px", "flow_node_min_height": "96px", "layout_min_column": "168px", "layout_editor_bar": "64px", "layout_preview_mobile": "390px", "layout_preview_tablet": "820px", "layout_preview_wall": "1200px"},
        "touch_target": "44px",
        "breakpoints": {"phone": 480, "tablet": 768, "desktop": 1200},
        "motion": {"fast": "120ms", "normal": "180ms", "slow": "280ms", "flow": "1.4s", "easing": "cubic-bezier(0.2, 0, 0, 1)"},
        "state": {"active": "#32E394", "disabled": "#71859A", "warning": "#FFD05C", "error": "#FF5B69"},
        "opacity": {"subtle": 0.08, "soft": 0.14, "medium": 0.35, "strong": 0.70},
        "color_picker": {
            "default_hue": 38,
            "saturation": "86%",
            "lightness": "56%",
            "temperature_warm": "#FFB45A",
            "temperature_neutral": "#FFF2D0",
            "temperature_cool": "#D9F1FF",
            "wheel": "conic-gradient(hsl(0 90% 55%), hsl(60 90% 55%), hsl(120 80% 45%), hsl(180 85% 45%), hsl(240 90% 60%), hsl(300 85% 55%), hsl(360 90% 55%))",
            "mask": "radial-gradient(circle, transparent 0 34%, black 36%)",
        },
    },
    "themes": [
        {
            "id": "cl_blue",
            "name": "CL Blue",
            "description": "Blu professionale",
            "mode": "dark",
            "colors": {},
        }
    ],
}
